# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

pip install pandas streamlit matplotlib seaborn

import streamlit as st

data = pd.read_csv("annual_data.csv")

# Sidebar filters
st.sidebar.header("Filters")
source_filter = st.sidebar.multiselect(
    "Select Source(s):",
    options=data["Source"].unique(),
    default=data["Source"].unique(),
)
year_range = st.sidebar.slider(
    "Select Year Range:",
    int(data["Year"].min()),
    int(data["Year"].max()),
    (int(data["Year"].min()), int(data["Year"].max()))
)

# Filter data based on user selections
filtered_data = data[
    (data["Source"].isin(source_filter)) &
    (data["Year"].between(year_range[0], year_range[1]))
]

# Title and raw data
st.title("Interactive Data Dashboard")
st.write("Explore the dataset interactively. Use the filters in the sidebar to customize the view.")

st.header("Raw Data")
st.write(filtered_data)

# Summary statistics
st.header("Summary Statistics")
st.write(filtered_data.describe())

# Line chart
st.header("Trend Over Time")
fig, ax = plt.subplots()
for source in filtered_data["Source"].unique():
    source_data = filtered_data[filtered_data["Source"] == source]
    ax.plot(source_data["Year"], source_data["Mean"], label=source)

ax.set_title("Yearly Mean Trends by Source")
ax.set_xlabel("Year")
ax.set_ylabel("Mean")
ax.legend()
st.pyplot(fig)

